// <auto-generated />
using System;
using CementerioApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CementerioApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260310011254_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("CementerioApp.Models.Difunto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cedula")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaFallecimiento")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LoteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LoteId")
                        .IsUnique();

                    b.ToTable("Difuntos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellido = "García",
                            Cedula = "12345678",
                            FechaFallecimiento = new DateTime(2010, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaNacimiento = new DateTime(1940, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LoteId = 1,
                            Nombre = "Juan",
                            Observaciones = "Descansa en paz"
                        },
                        new
                        {
                            Id = 2,
                            Apellido = "López",
                            Cedula = "87654321",
                            FechaFallecimiento = new DateTime(2018, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaNacimiento = new DateTime(1955, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LoteId = 2,
                            Nombre = "María",
                            Observaciones = "Siempre en nuestros corazones"
                        },
                        new
                        {
                            Id = 3,
                            Apellido = "Rodríguez",
                            Cedula = "11223344",
                            FechaFallecimiento = new DateTime(2020, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaNacimiento = new DateTime(1930, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LoteId = 5,
                            Nombre = "Carlos",
                            Observaciones = "En memoria eterna"
                        });
                });

            modelBuilder.Entity("CementerioApp.Models.Lote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Columna")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Fila")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Latitud")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitud")
                        .HasColumnType("REAL");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Lotes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Columna = 1,
                            Descripcion = "Lote sector A, fila 1, columna 1",
                            Estado = 1,
                            Fila = 1,
                            Latitud = -34.603700000000003,
                            Longitud = -58.381599999999999,
                            Sector = "A"
                        },
                        new
                        {
                            Id = 2,
                            Columna = 2,
                            Descripcion = "Lote sector A, fila 1, columna 2",
                            Estado = 1,
                            Fila = 1,
                            Latitud = -34.6038,
                            Longitud = -58.381700000000002,
                            Sector = "A"
                        },
                        new
                        {
                            Id = 3,
                            Columna = 3,
                            Descripcion = "Lote sector A, fila 1, columna 3",
                            Estado = 0,
                            Fila = 1,
                            Latitud = -34.603900000000003,
                            Longitud = -58.381799999999998,
                            Sector = "A"
                        },
                        new
                        {
                            Id = 4,
                            Columna = 1,
                            Descripcion = "Lote sector B, fila 1, columna 1",
                            Estado = 0,
                            Fila = 1,
                            Latitud = -34.603999999999999,
                            Longitud = -58.381900000000002,
                            Sector = "B"
                        },
                        new
                        {
                            Id = 5,
                            Columna = 2,
                            Descripcion = "Lote sector B, fila 1, columna 2",
                            Estado = 1,
                            Fila = 1,
                            Latitud = -34.604100000000003,
                            Longitud = -58.381999999999998,
                            Sector = "B"
                        },
                        new
                        {
                            Id = 6,
                            Columna = 3,
                            Descripcion = "Lote sector B, fila 1, columna 3",
                            Estado = 0,
                            Fila = 1,
                            Latitud = -34.604199999999999,
                            Longitud = -58.382100000000001,
                            Sector = "B"
                        },
                        new
                        {
                            Id = 7,
                            Columna = 1,
                            Descripcion = "Lote sector C, fila 1, columna 1",
                            Estado = 0,
                            Fila = 1,
                            Latitud = -34.604300000000002,
                            Longitud = -58.382199999999997,
                            Sector = "C"
                        },
                        new
                        {
                            Id = 8,
                            Columna = 2,
                            Descripcion = "Lote sector C, fila 1, columna 2",
                            Estado = 0,
                            Fila = 1,
                            Latitud = -34.604399999999998,
                            Longitud = -58.382300000000001,
                            Sector = "C"
                        },
                        new
                        {
                            Id = 9,
                            Columna = 3,
                            Descripcion = "Lote sector C, fila 1, columna 3",
                            Estado = 1,
                            Fila = 1,
                            Latitud = -34.604500000000002,
                            Longitud = -58.382399999999997,
                            Sector = "C"
                        });
                });

            modelBuilder.Entity("CementerioApp.Models.Difunto", b =>
                {
                    b.HasOne("CementerioApp.Models.Lote", "Lote")
                        .WithOne("Difunto")
                        .HasForeignKey("CementerioApp.Models.Difunto", "LoteId");

                    b.Navigation("Lote");
                });

            modelBuilder.Entity("CementerioApp.Models.Lote", b =>
                {
                    b.Navigation("Difunto");
                });
#pragma warning restore 612, 618
        }
    }
}
